/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users (paginated) — Admin only */
        get: operations["UserController_getAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter users with pagination — Admin only */
        get: operations["UserController_filterUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID — Admin only */
        get: operations["UserController_getUserById"];
        /** Update user by ID — Admin only */
        put: operations["UserController_updateUser"];
        post?: never;
        /** Delete user by ID — Admin only */
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-generation/text-to-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an image from a text prompt */
        post: operations["ImageGenerationModelController_textToImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/character-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a character and generate its image using AI */
        post: operations["CharacterWorkflowController_createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audio-model/sync-voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AudioModelController_syncAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audio-model/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filter and paginate available voices
         * @description Retrieves available voices with pagination, text search,
         *             and optional filters for accent, age, and gender.
         */
        get: operations["AudioModelController_filterVoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/character/characterById/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a character by ID
         * @description Fetches a full character document by its unique ID.
         */
        get: operations["CharacterController_getCharacterById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/character/getUserCharacters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all characters of a user
         * @description Fetches all characters created by a specific user ID, returning full documents.
         */
        get: operations["CharacterController_getCharactersByUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/character/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete character by ID
         * @description Deletes a character from the database by its unique ID.
         */
        delete: operations["CharacterController_deleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get episode by ID
         * @description Fetches a single episode by its unique ID with populated character and user information.
         */
        get: operations["EpisodeController_getEpisodeById"];
        put?: never;
        post?: never;
        /**
         * Delete episode by ID
         * @description Permanently deletes an episode from the database by its unique ID.
         */
        delete: operations["EpisodeController_deleteEpisode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filter and paginate episodes
         * @description Retrieve episodes with optional filters (userId, characterId, art_style, visibility) and pagination support. Returns total count and page information.
         */
        get: operations["EpisodeController_filterEpisodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode-orchestrator/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate full AI episode video
         * @description Triggers the pipeline to generate a complete AI video episode from a story and character. It uses Gemini for scene breakdown, image generation, TTS, and video synthesis before merging and uploading to S3.
         */
        post: operations["EpisodeOrchestratorController_generateEpisode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode-orchestrator/generate-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EpisodeOrchestratorController_generateStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode-orchestrator/merge-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EpisodeOrchestratorController_mergeScenesTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/create-subscription-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a subscription checkout session
         * @description Creates a new Stripe checkout session for purchasing a subscription plan.
         */
        post: operations["StripeController_createSubscriptionCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/create-token-pack-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a token pack checkout session
         * @description Creates a new Stripe checkout session for purchasing a token pack.
         */
        post: operations["StripeController_createTokenPackCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle Stripe webhook events
         * @description Processes incoming Stripe webhook events. This endpoint is public and should be configured in your Stripe dashboard. Verifies webhook signature and processes events like payment success, failure, etc.
         */
        post: operations["StripeController_handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all subscription plans with pagination */
        get: operations["PlansController_getAllPlans"];
        put?: never;
        /** Create a new subscription plan — Admin only */
        post: operations["PlansController_createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all active subscription plans */
        get: operations["PlansController_getActivePlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/tier/{tier}/{interval}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get plan by tier and interval */
        get: operations["PlansController_getPlanByTier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get plan by ID */
        get: operations["PlansController_getPlanById"];
        /** Update subscription plan — Admin only */
        put: operations["PlansController_updatePlan"];
        post?: never;
        /** Delete subscription plan (soft delete) — Admin only */
        delete: operations["PlansController_deletePlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/token-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all available token packs */
        get: operations["PlansController_getAllTokenPacks"];
        put?: never;
        /** Create a new token pack — Admin only */
        post: operations["PlansController_createTokenPack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/token-packs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update token pack — Admin only */
        put: operations["PlansController_updateTokenPack"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/calculate-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate token cost for video duration and resolution */
        get: operations["PlansController_calculateCost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/transactions/my-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user payment history */
        get: operations["PlansController_getMyTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserDto: {
            /**
             * @description Updated full name of the user
             * @example John Doe Updated
             */
            fullName?: string;
            /**
             * @description Updated email address of the user
             * @example john_updated@example.com
             */
            email?: string;
            /**
             * @description New password for the user (optional)
             * @example newstrongpassword123
             */
            password?: string;
            /**
             * @description Updated gender (optional)
             * @example female
             * @enum {string}
             */
            gender?: "male" | "female" | "other";
            /**
             * @description Updated user role (optional)
             * @example admin
             * @enum {string}
             */
            role?: "admin" | "user";
            /**
             * @description Updated account status (optional)
             * @example suspended
             * @enum {string}
             */
            status?: "active" | "inactive" | "suspended";
            /**
             * @description Updated profile picture URL (optional)
             * @example https://example.com/new-profile.jpg
             */
            profilePic?: string;
            /** @description Current subscription plan ID */
            currentPlan?: Record<string, never>;
            /**
             * @description Remaining tokens from subscription
             * @example 450
             */
            tokensRemaining?: number;
            /**
             * @description Purchased tokens from token packs
             * @example 100
             */
            purchasedTokens?: number;
            /**
             * Format: date-time
             * @description Next token reset date
             */
            tokensResetDate?: string;
        };
        CreateUserDto: {
            /**
             * @description Full name of the user
             * @example John Doe
             */
            fullName: string;
            /**
             * @description Email address of the user (must be unique)
             * @example john@example.com
             */
            email: string;
            /**
             * @description User password (will be hashed before saving)
             * @example strongpassword123
             */
            password: string;
            /**
             * @description Gender of the user
             * @example male
             * @enum {string}
             */
            gender: "male" | "female" | "other";
            /**
             * @description User role in the system
             * @example user
             * @enum {string}
             */
            role: "admin" | "user";
            /**
             * @description Account status (optional, defaults to active)
             * @example active
             * @enum {string}
             */
            status?: "active" | "inactive" | "suspended";
            /**
             * @description Profile picture URL (optional)
             * @example https://example.com/profile.jpg
             */
            profilePic?: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        TextToImageDto: {
            /** @example A futuristic robot in Tokyo at night */
            prompt: string;
            /**
             * @default 1
             * @example 1
             */
            num_images: number;
            /**
             * @default png
             * @example png
             * @enum {string}
             */
            output_format: "jpeg" | "png" | "webp";
            /**
             * @default 9:16
             * @example 9:16
             */
            aspect_ratio: string;
        };
        AppearanceDto: {
            hair_color: string;
            hair_style: string;
            eye_color: string;
            skin_tone: string;
            outfit: string;
            accessories: string[];
        };
        CreateCharacterDto: {
            name: string;
            /** @enum {string} */
            art_style: "anime" | "cartoon" | "realistic" | "fantasy" | "sci-fi" | "3D";
            /** @enum {string} */
            gender: "male" | "female";
            /** @enum {string} */
            age_group: "child" | "teen" | "youngAdult" | "adult" | "elderly";
            personality_traits: ("Heroic" | "Funny" | "Mysterious" | "Calm" | "Energetic" | "Wise" | "Brave" | "Shy" | "Confident" | "Quirky" | "Serious" | "Playful")[];
            /** @enum {string} */
            voice_tone?: "cheerful" | "serious" | "mysterious" | "energetic" | "calm" | "dramatic";
            /** @enum {string} */
            voice_accent?: "neutral" | "american" | "british" | "australian";
            appearance: components["schemas"]["AppearanceDto"];
            backstory?: string;
            Image?: string;
            is_premium?: boolean;
            is_sample?: boolean;
            is_template?: boolean;
            /** @description If true, character will have a custom voice and voice_tone/voice_accent become required. */
            createcustomvoice?: boolean;
            /** @description Reference to the Voice document ID */
            characterVoice?: string;
            /** @description User who created this character */
            created_by: string;
        };
        CreateSubscriptionCheckoutDto: {
            /**
             * @description User ID for the subscription
             * @example 507f1f77bcf86cd799439011
             */
            userId: string;
            /**
             * @description ID of the plan to subscribe to
             * @example plan_123456789
             */
            planId: string;
        };
        CreateTokenPackCheckoutDto: {
            /**
             * @description User ID for the token pack purchase
             * @example 507f1f77bcf86cd799439011
             */
            userId: string;
            /**
             * @description ID of the token pack to purchase
             * @example pack_123456789
             */
            tokenPackId: string;
        };
        CreatePlanDto: {
            /**
             * @description Subscription tier level
             * @example CREATOR
             * @enum {string}
             */
            tier: "STARTER" | "CREATOR" | "PRO" | "AGENCY";
            /**
             * @description Display name of the plan
             * @example Creator Plan
             */
            name: string;
            /**
             * @description Billing interval (monthly or annual)
             * @example MONTHLY
             * @enum {string}
             */
            interval: "MONTHLY" | "ANNUAL";
            /**
             * @description Price in USD
             * @example 49
             */
            priceUSD: number;
            /**
             * @description Number of tokens per billing period
             * @example 450
             */
            tokensPerPeriod: number;
            /**
             * @description Queue priority level for video generation
             * @example 20
             * @enum {number}
             */
            queuePriority: 10 | 20 | 30 | 40;
            /**
             * @description List of features included in the plan
             * @example [
             *       "Priority queue",
             *       "All resolutions",
             *       "Faster rendering"
             *     ]
             */
            features: string[];
            /**
             * @description Whether the plan is active and available for purchase
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Detailed description of the plan
             * @example Perfect for influencers and regular content creators
             */
            description?: string;
        };
        UpdatePlanDto: {
            /**
             * @description Subscription tier level
             * @example CREATOR
             * @enum {string}
             */
            tier?: "STARTER" | "CREATOR" | "PRO" | "AGENCY";
            /**
             * @description Display name of the plan
             * @example Creator Plan
             */
            name?: string;
            /**
             * @description Billing interval (monthly or annual)
             * @example MONTHLY
             * @enum {string}
             */
            interval?: "MONTHLY" | "ANNUAL";
            /**
             * @description Price in USD
             * @example 49
             */
            priceUSD?: number;
            /**
             * @description Number of tokens per billing period
             * @example 450
             */
            tokensPerPeriod?: number;
            /**
             * @description Queue priority level for video generation
             * @example 20
             * @enum {number}
             */
            queuePriority?: 10 | 20 | 30 | 40;
            /**
             * @description List of features included in the plan
             * @example [
             *       "Priority queue",
             *       "All resolutions",
             *       "Faster rendering"
             *     ]
             */
            features?: string[];
            /**
             * @description Whether the plan is active and available for purchase
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Detailed description of the plan
             * @example Perfect for influencers and regular content creators
             */
            description?: string;
        };
        CreateTokenPackDto: {
            /**
             * @description Display name of the token pack
             * @example Medium Pack
             */
            name: string;
            /**
             * @description Number of tokens in the pack
             * @example 250
             */
            tokens: number;
            /**
             * @description Price in USD
             * @example 25
             */
            priceUSD: number;
            /**
             * @description Whether the token pack is active and available for purchase
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Detailed description of the token pack
             * @example Most popular token pack - best value!
             */
            description?: string;
        };
        UpdateTokenPackDto: {
            /**
             * @description Display name of the token pack
             * @example Medium Pack
             */
            name?: string;
            /**
             * @description Number of tokens in the pack
             * @example 250
             */
            tokens?: number;
            /**
             * @description Price in USD
             * @example 25
             */
            priceUSD?: number;
            /**
             * @description Whether the token pack is active and available for purchase
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Detailed description of the token pack
             * @example Most popular token pack - best value!
             */
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UserController_getAllUsers: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_filterUsers: {
        parameters: {
            query?: {
                search?: string;
                gender?: "male" | "female" | "other";
                role?: "admin" | "user";
                status?: string;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImageGenerationModelController_textToImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextToImageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CharacterWorkflowController_createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCharacterDto"];
            };
        };
        responses: {
            /** @description Character created and image generated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Prompt generation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to save character to database */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Image generation failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AudioModelController_syncAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AudioModelController_filterVoices: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                accent?: string;
                age?: string;
                gender?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Voices fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CharacterController_getCharacterById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Character ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CharacterController_getCharactersByUser: {
        parameters: {
            query: {
                /** @description User ID */
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Characters fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CharacterController_deleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Character ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    EpisodeController_getEpisodeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episode fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Failed to fetch episode */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_deleteEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episode deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Failed to delete episode */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_filterEpisodes: {
        parameters: {
            query?: {
                /** @description Filter by user ID */
                userId?: string;
                /** @description Filter by character ID */
                characterId?: string;
                /** @description Filter by art style */
                art_style?: "cartoon" | "anime" | "realistic" | "fantasy" | "scifi";
                /** @description Filter by visibility */
                visibility?: "onlyme" | "public";
                /** @description Page number */
                page?: number;
                /** @description Results per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episodes filtered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal server error - Failed to filter episodes */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeOrchestratorController_generateEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Full story text used to generate episode scenes
                     * @example Once upon a time in a futuristic city, Luna the AI explorer discovers an ancient robot buried under neon ruins...
                     */
                    story: string;
                    character: {
                        /** @example 693024dcd41be0486063e2a6 */
                        _id?: string;
                        /** @example Luna the Explorer */
                        name?: string;
                        /** @example https://example-bucket.s3.amazonaws.com/characters/luna.png */
                        Image?: string;
                        characterVoice?: {
                            /** @example 21m00Tcm4TlvDq8ikWAM */
                            voice_id?: string;
                        };
                    };
                    /**
                     * @description User ID who initiated the episode generation
                     * @example 64f22af9b3f8d8d3b93ef1a4
                     */
                    userId: string;
                    /**
                     * @description Optional art style for generated visuals
                     * @example realistic
                     */
                    artStyle?: string;
                    /**
                     * @description Target video resolution
                     * @example 720p
                     * @enum {string}
                     */
                    resolution?: "480p" | "720p" | "1080p";
                    /**
                     * @description Video generation mode
                     * @example wan_lipsync
                     * @enum {string}
                     */
                    mode?: "wan_lipsync" | "external_merge";
                };
            };
        };
        responses: {
            /** @description Successfully generated episode */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode generation failed due to internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeOrchestratorController_generateStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeOrchestratorController_mergeScenesTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_createSubscriptionCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionCheckoutDto"];
            };
        };
        responses: {
            /** @description Subscription checkout session created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request - User not found or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_createTokenPackCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenPackCheckoutDto"];
            };
        };
        responses: {
            /** @description Token pack checkout session created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request - User not found or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_handleWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description Stripe webhook signature for event verification */
                "stripe-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid signature or missing raw body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Failed to process webhook */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getAllPlans: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plans fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanDto"];
            };
        };
        responses: {
            /** @description Plan created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getActivePlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active plans fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getPlanByTier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier: string;
                interval: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getPlanById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_updatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanDto"];
            };
        };
        responses: {
            /** @description Plan updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_deletePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getAllTokenPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token packs fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_createTokenPack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenPackDto"];
            };
        };
        responses: {
            /** @description Token pack created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_updateTokenPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTokenPackDto"];
            };
        };
        responses: {
            /** @description Token pack updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_calculateCost: {
        parameters: {
            query: {
                /** @description Duration in seconds */
                duration: number;
                resolution: "480P" | "720P" | "1080P";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost calculated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getMyTransactions: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
