/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users (paginated) — Admin only */
        get: operations["UserController_getAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter users with pagination — Admin only */
        get: operations["UserController_filterUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID — Admin only */
        get: operations["UserController_getUserById"];
        /** Update user by ID — Admin only */
        put: operations["UserController_updateUser"];
        post?: never;
        /** Delete user by ID — Admin only */
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-generation/text-to-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an image from a text prompt */
        post: operations["ImageGenerationModelController_textToImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/character-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a character and generate its image using AI
         * @description Generate a character image from text description or transform a user-provided image. If userGivenImage is provided, the system will use image-to-image transformation; otherwise, it will generate from scratch using text-to-image.
         */
        post: operations["CharacterWorkflowController_createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audio-model/sync-voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AudioModelController_syncAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audio-model/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filter and paginate available voices
         * @description Retrieves available voices with pagination, text search,
         *             and optional filters for accent, age, and gender.
         */
        get: operations["AudioModelController_filterVoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audio-model/text-to-speech-with-timestamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate speech audio with word-level timestamps
         * @description Converts text to speech using ElevenLabs API and returns:
         *             - Audio URL (base64 or file path)
         *             - Word-level alignment with timestamps
         *             - Total audio duration
         *
         *             Supports customizable voice settings and optional file saving.
         */
        post: operations["AudioModelController_textToSpeechWithTimestamps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/character/characterById/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a character by ID
         * @description Fetches a full character document by its unique ID.
         */
        get: operations["CharacterController_getCharacterById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/character/getUserCharacters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all characters of a user
         * @description Fetches all characters created by a specific user ID, returning full documents.
         */
        get: operations["CharacterController_getCharactersByUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/character/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete character by ID
         * @description Deletes a character from the database by its unique ID.
         */
        delete: operations["CharacterController_deleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get episode by ID
         * @description Fetches a single episode by its unique ID with populated character and user information.
         */
        get: operations["EpisodeController_getEpisodeById"];
        put?: never;
        post?: never;
        /**
         * Delete episode by ID
         * @description Permanently deletes an episode from the database by its unique ID.
         */
        delete: operations["EpisodeController_deleteEpisode"];
        options?: never;
        head?: never;
        /**
         * Update episode by ID
         * @description Updates an existing episode by its unique ID. All fields are optional. Only provided fields will be updated.
         */
        patch: operations["EpisodeController_updateEpisode"];
        trace?: never;
    };
    "/api/v1/episode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filter and paginate episodes
         * @description Retrieve episodes with optional filters (userId, characterId, art_style, visibility) and pagination support. Returns total count and page information.
         */
        get: operations["EpisodeController_filterEpisodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode/{id}/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track episode watch
         * @description Records a watch event for an episode. Creates a watch history record and atomically increments the episode watch count. Can be called multiple times per user to track repeated views.
         */
        post: operations["EpisodeController_trackWatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Like or unlike an episode
         * @description Toggles like status for the current user on an episode. If already liked, removes the like. If not liked, adds a like. Uses atomic operations to prevent race conditions.
         */
        post: operations["EpisodeController_toggleLike"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track episode download
         * @description Records a download event and returns the episode video URL. Creates a download history record and atomically increments the download count.
         */
        post: operations["EpisodeController_trackDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode/{id}/engagement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user engagement status
         * @description Retrieves the current user's engagement status for a specific episode, including like status, watch history, and download status.
         */
        get: operations["EpisodeController_getUserEngagement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode-orchestrator/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate full AI episode video
         * @description Triggers the pipeline to generate a complete AI video episode from a story and character. It uses Gemini for scene breakdown, image generation, TTS, and video synthesis before merging and uploading to S3.
         */
        post: operations["EpisodeOrchestratorController_generateEpisode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode-orchestrator/generate-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EpisodeOrchestratorController_generateStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode-orchestrator/merge-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EpisodeOrchestratorController_mergeScenesTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload file(s) to S3
         * @description Upload one or multiple files to S3 storage. Files are stored in the specified folder with unique filenames.
         */
        post: operations["StorageController_uploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete file from S3
         * @description Delete a file from S3 storage using its key (path in bucket).
         */
        delete: operations["StorageController_deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/create-subscription-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a subscription checkout session
         * @description Creates a new Stripe checkout session for purchasing a subscription plan.
         */
        post: operations["StripeController_createSubscriptionCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/create-token-pack-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a token pack checkout session
         * @description Creates a new Stripe checkout session for purchasing a token pack.
         */
        post: operations["StripeController_createTokenPackCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle Stripe webhook events
         * @description Processes incoming Stripe webhook events. This endpoint is public and should be configured in your Stripe dashboard. Verifies webhook signature and processes events like payment success, failure, etc.
         */
        post: operations["StripeController_handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new subscription plan — Admin only */
        post: operations["PlansController_createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/all-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all subscription plans with pagination */
        get: operations["PlansController_getAllPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all active subscription plans */
        get: operations["PlansController_getActivePlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/tier/{tier}/{interval}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get plan by tier and interval */
        get: operations["PlansController_getPlanByTier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/getPlanById/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get plan by ID */
        get: operations["PlansController_getPlanById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/updatePlanById/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update subscription plan — Admin only */
        put: operations["PlansController_updatePlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/deletePlanById/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete subscription plan (soft delete) — Admin only */
        delete: operations["PlansController_deletePlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/token-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all available token packs */
        get: operations["PlansController_getAllTokenPacks"];
        put?: never;
        /** Create a new token pack — Admin only */
        post: operations["PlansController_createTokenPack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/token-packs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update token pack — Admin only */
        put: operations["PlansController_updateTokenPack"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/calculate-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate token cost for video duration and resolution */
        get: operations["PlansController_calculateCost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/transactions/my-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user payment history */
        get: operations["PlansController_getMyTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episode/{episodeId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get episode comments
         * @description Retrieves all top-level comments for an episode with pagination. Supports sorting by newest or oldest. Excludes deleted comments.
         */
        get: operations["CommentController_getEpisodeComments"];
        put?: never;
        /**
         * Create a comment or reply
         * @description Creates a new comment on an episode or a reply to an existing comment. Supports @mentions and tracks reply-to relationships for nested comment threads.
         */
        post: operations["CommentController_createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comment/{commentId}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get comment replies
         * @description Retrieves all replies to a specific comment with pagination. Returns replies sorted oldest first. Excludes deleted replies.
         */
        get: operations["CommentController_getCommentReplies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comment/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete your comment
         * @description Soft deletes your comment. Only the comment author can delete. The comment content is replaced with "[deleted]" to preserve thread context.
         */
        delete: operations["CommentController_deleteComment"];
        options?: never;
        head?: never;
        /**
         * Update your comment
         * @description Updates the content of your own comment. Only the comment author can edit. Marks the comment as edited after update.
         */
        patch: operations["CommentController_updateComment"];
        trace?: never;
    };
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserDto: {
            /**
             * @description Updated full name of the user
             * @example John Doe Updated
             */
            fullName?: string;
            /**
             * @description Updated email address of the user
             * @example john_updated@example.com
             */
            email?: string;
            /**
             * @description New password for the user (optional)
             * @example newstrongpassword123
             */
            password?: string;
            /**
             * @description Updated gender (optional)
             * @example female
             * @enum {string}
             */
            gender?: "male" | "female" | "other";
            /**
             * @description Updated user role (optional)
             * @example admin
             * @enum {string}
             */
            role?: "admin" | "user";
            /**
             * @description Updated account status (optional)
             * @example suspended
             * @enum {string}
             */
            status?: "active" | "inactive" | "suspended";
            /**
             * @description Updated profile picture URL (optional)
             * @example https://example.com/new-profile.jpg
             */
            profilePic?: string;
            /** @description Current subscription plan ID */
            currentPlan?: Record<string, never>;
            /**
             * @description Remaining tokens from subscription
             * @example 450
             */
            tokensRemaining?: number;
            /**
             * @description Purchased tokens from token packs
             * @example 100
             */
            purchasedTokens?: number;
            /**
             * Format: date-time
             * @description Next token reset date
             */
            tokensResetDate?: string;
        };
        CreateUserDto: {
            /**
             * @description Full name of the user
             * @example John Doe
             */
            fullName: string;
            /**
             * @description Email address of the user (must be unique)
             * @example john@example.com
             */
            email: string;
            /**
             * @description User password (will be hashed before saving)
             * @example strongpassword123
             */
            password: string;
            /**
             * @description Gender of the user
             * @example male
             * @enum {string}
             */
            gender: "male" | "female" | "other";
            /**
             * @description User role in the system
             * @example user
             * @enum {string}
             */
            role: "admin" | "user";
            /**
             * @description Account status (optional, defaults to active)
             * @example active
             * @enum {string}
             */
            status?: "active" | "inactive" | "suspended";
            /**
             * @description Profile picture URL (optional)
             * @example https://example.com/profile.jpg
             */
            profilePic?: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        TextToImageDto: {
            /** @example A futuristic robot in Tokyo at night */
            prompt: string;
            /**
             * @default 1
             * @example 1
             */
            num_images: number;
            /**
             * @default png
             * @example png
             * @enum {string}
             */
            output_format: "jpeg" | "png" | "webp";
            /**
             * @default 9:16
             * @example 9:16
             */
            aspect_ratio: string;
        };
        AppearanceDto: {
            hair_color: string;
            hair_style: string;
            eye_color: string;
            skin_tone: string;
            outfit: string;
            accessories: string[];
        };
        CreateCharacterDto: {
            name: string;
            /** @enum {string} */
            art_style: "anime" | "cartoon" | "realistic" | "fantasy" | "sci-fi" | "3D";
            /** @enum {string} */
            gender: "male" | "female";
            /** @enum {string} */
            age_group: "child" | "teen" | "youngAdult" | "adult" | "elderly";
            personality_traits: ("Heroic" | "Funny" | "Mysterious" | "Calm" | "Energetic" | "Wise" | "Brave" | "Shy" | "Confident" | "Quirky" | "Serious" | "Playful")[];
            /** @enum {string} */
            voice_tone?: "cheerful" | "serious" | "mysterious" | "energetic" | "calm" | "dramatic";
            /** @enum {string} */
            voice_accent?: "neutral" | "american" | "british" | "australian";
            appearance: components["schemas"]["AppearanceDto"];
            backstory?: string;
            Image?: string;
            /** @description S3 URL of user-provided image for character generation */
            userGivenImage?: string;
            is_premium?: boolean;
            is_sample?: boolean;
            is_template?: boolean;
            /** @description If true, character will have a custom voice and voice_tone/voice_accent become required. */
            createcustomvoice?: boolean;
            /** @description Reference to the Voice document ID */
            characterVoice?: string;
            /** @description User who created this character */
            created_by: string;
        };
        TextToSpeechDto: {
            /**
             * @description The text to convert to speech
             * @example Hello! This is a test of the text to speech system.
             */
            text: string;
            /**
             * @description The voice ID from ElevenLabs to use for speech generation
             * @example EXAVITQu4vr4xnSDxMaL
             */
            voiceId: string;
            /**
             * @description Model ID to use for speech generation
             * @default eleven_turbo_v2
             * @example eleven_turbo_v2
             */
            model_id: string;
            /**
             * @description Output audio format
             * @default mp3
             * @example mp3
             * @enum {string}
             */
            output_format: "mp3" | "wav";
            /**
             * @description Voice stability (0.0 to 1.0)
             * @default 0.5
             * @example 0.5
             */
            stability: number;
            /**
             * @description Similarity boost (0.0 to 1.0)
             * @default 0.8
             * @example 0.8
             */
            similarity_boost: number;
            /**
             * @description Voice style (0.0 to 1.0)
             * @default 0
             * @example 0
             */
            style: number;
            /**
             * @description Enable speaker boost for enhanced clarity
             * @default true
             * @example true
             */
            speaker_boost: boolean;
            /**
             * @description Whether to save the audio file to disk
             * @default false
             * @example true
             */
            saveToFile: boolean;
        };
        CreateSubscriptionCheckoutDto: {
            /**
             * @description User ID for the subscription
             * @example 507f1f77bcf86cd799439011
             */
            userId: string;
            /**
             * @description ID of the plan to subscribe to
             * @example plan_123456789
             */
            planId: string;
        };
        CreateTokenPackCheckoutDto: {
            /**
             * @description User ID for the token pack purchase
             * @example 507f1f77bcf86cd799439011
             */
            userId: string;
            /**
             * @description ID of the token pack to purchase
             * @example pack_123456789
             */
            tokenPackId: string;
        };
        CreatePlanDto: {
            /**
             * @description Subscription tier level
             * @example CREATOR
             * @enum {string}
             */
            tier: "STARTER" | "CREATOR" | "PRO" | "AGENCY";
            /**
             * @description Display name of the plan
             * @example Creator Plan
             */
            name: string;
            /**
             * @description Billing interval (monthly or annual)
             * @example MONTHLY
             * @enum {string}
             */
            interval: "MONTHLY" | "ANNUAL";
            /**
             * @description Price in USD
             * @example 49
             */
            priceUSD: number;
            /**
             * @description Number of tokens per billing period
             * @example 450
             */
            tokensPerPeriod: number;
            /**
             * @description Queue priority level for video generation
             * @example 20
             * @enum {number}
             */
            queuePriority: 10 | 20 | 30 | 40;
            /**
             * @description List of features included in the plan
             * @example [
             *       "Priority queue",
             *       "All resolutions",
             *       "Faster rendering"
             *     ]
             */
            features: string[];
            /**
             * @description Whether the plan is active and available for purchase
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Detailed description of the plan
             * @example Perfect for influencers and regular content creators
             */
            description?: string;
        };
        UpdatePlanDto: {
            /**
             * @description Subscription tier level
             * @example CREATOR
             * @enum {string}
             */
            tier?: "STARTER" | "CREATOR" | "PRO" | "AGENCY";
            /**
             * @description Display name of the plan
             * @example Creator Plan
             */
            name?: string;
            /**
             * @description Billing interval (monthly or annual)
             * @example MONTHLY
             * @enum {string}
             */
            interval?: "MONTHLY" | "ANNUAL";
            /**
             * @description Price in USD
             * @example 49
             */
            priceUSD?: number;
            /**
             * @description Number of tokens per billing period
             * @example 450
             */
            tokensPerPeriod?: number;
            /**
             * @description Queue priority level for video generation
             * @example 20
             * @enum {number}
             */
            queuePriority?: 10 | 20 | 30 | 40;
            /**
             * @description List of features included in the plan
             * @example [
             *       "Priority queue",
             *       "All resolutions",
             *       "Faster rendering"
             *     ]
             */
            features?: string[];
            /**
             * @description Whether the plan is active and available for purchase
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Detailed description of the plan
             * @example Perfect for influencers and regular content creators
             */
            description?: string;
        };
        CreateTokenPackDto: {
            /**
             * @description Display name of the token pack
             * @example Medium Pack
             */
            name: string;
            /**
             * @description Number of tokens in the pack
             * @example 250
             */
            tokens: number;
            /**
             * @description Price in USD
             * @example 25
             */
            priceUSD: number;
            /**
             * @description Whether the token pack is active and available for purchase
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Detailed description of the token pack
             * @example Most popular token pack - best value!
             */
            description?: string;
        };
        UpdateTokenPackDto: {
            /**
             * @description Display name of the token pack
             * @example Medium Pack
             */
            name?: string;
            /**
             * @description Number of tokens in the pack
             * @example 250
             */
            tokens?: number;
            /**
             * @description Price in USD
             * @example 25
             */
            priceUSD?: number;
            /**
             * @description Whether the token pack is active and available for purchase
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Detailed description of the token pack
             * @example Most popular token pack - best value!
             */
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UserController_getAllUsers: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_filterUsers: {
        parameters: {
            query?: {
                search?: string;
                gender?: "male" | "female" | "other";
                role?: "admin" | "user";
                status?: string;
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ImageGenerationModelController_textToImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextToImageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CharacterWorkflowController_createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCharacterDto"];
            };
        };
        responses: {
            /** @description Character created and image generated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Prompt generation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to save character to database */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Image generation failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AudioModelController_syncAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AudioModelController_filterVoices: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                accent?: string;
                age?: string;
                gender?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Voices fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AudioModelController_textToSpeechWithTimestamps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextToSpeechDto"];
            };
        };
        responses: {
            /** @description Speech generated successfully with timestamps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CharacterController_getCharacterById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Character ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CharacterController_getCharactersByUser: {
        parameters: {
            query: {
                /** @description User ID */
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Characters fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    CharacterController_deleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Character ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    EpisodeController_getEpisodeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episode fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Failed to fetch episode */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_deleteEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episode deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Failed to delete episode */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_updateEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID to update */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Updated story content... */
                    story?: string;
                    /**
                     * @example wan_lipsync
                     * @enum {string}
                     */
                    mode?: "wan_lipsync" | "external_merge";
                    /**
                     * @example 720p
                     * @enum {string}
                     */
                    resolution?: "480p" | "720p" | "1080p";
                    /**
                     * @example anime
                     * @enum {string}
                     */
                    art_style?: "cartoon" | "anime" | "realistic" | "fantasy" | "scifi";
                    /**
                     * @example public
                     * @enum {string}
                     */
                    visibility?: "onlyme" | "public";
                    /** @example 200 */
                    watchCount?: number;
                    /** @example 50 */
                    likes?: number;
                    /** @example 10 */
                    shares?: number;
                    /** @example 15 */
                    downloads?: number;
                    /** @example true */
                    featured?: boolean;
                    /** @example 180 */
                    duration?: number;
                    /** @example https://example.com/updated-video.mp4 */
                    finalVideoUrl?: string;
                    /** @example https://example.com/updated-subtitles.srt */
                    subtitleUrl?: string;
                };
            };
        };
        responses: {
            /** @description Episode updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Failed to update episode */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_filterEpisodes: {
        parameters: {
            query?: {
                /** @description Filter by user ID */
                userId?: string;
                /** @description Filter by character ID */
                characterId?: string;
                /** @description Filter by art style */
                art_style?: "cartoon" | "anime" | "realistic" | "fantasy" | "scifi";
                /** @description Filter by visibility */
                visibility?: "onlyme" | "public";
                /** @description Page number */
                page?: number;
                /** @description Results per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episodes filtered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal server error - Failed to filter episodes */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_trackWatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watch tracked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Could not track watch */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_toggleLike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Like toggled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Could not toggle like */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_trackDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download tracked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found or video not available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Could not track download */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeController_getUserEngagement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User engagement fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Could not fetch user engagement */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeOrchestratorController_generateEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Full story text used to generate episode scenes
                     * @example Once upon a time in a futuristic city, Luna the AI explorer discovers an ancient robot buried under neon ruins...
                     */
                    story: string;
                    character: {
                        /** @example 693ab724d639a8b3373ea54d */
                        _id?: string;
                        /** @example Luna the Explorer */
                        name?: string;
                        /** @example https://example-bucket.s3.amazonaws.com/characters/luna.png */
                        Image?: string;
                        characterVoice?: {
                            /** @example 21m00Tcm4TlvDq8ikWAM */
                            voice_id?: string;
                        };
                    };
                    /**
                     * @description User ID who initiated the episode generation
                     * @example 64f22af9b3f8d8d3b93ef1a4
                     */
                    userId: string;
                    /**
                     * @description Optional art style for generated visuals
                     * @example realistic
                     */
                    artStyle?: string;
                    /**
                     * @description Target video resolution
                     * @example 720p
                     * @enum {string}
                     */
                    resolution?: "480p" | "720p" | "1080p";
                    /**
                     * @description Video generation mode
                     * @example wan_lipsync
                     * @enum {string}
                     */
                    mode?: "wan_lipsync" | "external_merge";
                };
            };
        };
        responses: {
            /** @description Successfully generated episode */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Episode generation failed due to internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeOrchestratorController_generateStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EpisodeOrchestratorController_mergeScenesTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StorageController_uploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Files to upload (supports multiple files) */
                    files: string[];
                    /**
                     * @description Folder path in S3 bucket
                     * @default uploads
                     */
                    folder?: string;
                };
            };
        };
        responses: {
            /** @description Files uploaded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StorageController_deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description S3 object key (path) of the file to delete */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal server error - Failed to delete file */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_createSubscriptionCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionCheckoutDto"];
            };
        };
        responses: {
            /** @description Subscription checkout session created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request - User not found or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_createTokenPackCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenPackCheckoutDto"];
            };
        };
        responses: {
            /** @description Token pack checkout session created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad request - User not found or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeController_handleWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description Stripe webhook signature for event verification */
                "stripe-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid signature or missing raw body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Failed to process webhook */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanDto"];
            };
        };
        responses: {
            /** @description Plan created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getAllPlans: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plans fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getActivePlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active plans fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getPlanByTier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier: string;
                interval: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getPlanById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_updatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanDto"];
            };
        };
        responses: {
            /** @description Plan updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_deletePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getAllTokenPacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token packs fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_createTokenPack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenPackDto"];
            };
        };
        responses: {
            /** @description Token pack created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_updateTokenPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTokenPackDto"];
            };
        };
        responses: {
            /** @description Token pack updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_calculateCost: {
        parameters: {
            query: {
                /** @description Duration in seconds */
                duration: number;
                resolution: "480P" | "720P" | "1080P";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost calculated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PlansController_getMyTransactions: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transactions fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentController_getEpisodeComments: {
        parameters: {
            query?: {
                /** @description Sort order */
                sortBy?: "newest" | "oldest";
                /** @description Page number */
                page?: unknown;
                /** @description Comments per page */
                limit?: unknown;
            };
            header?: never;
            path: {
                /** @description Episode ID */
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal server error - Could not fetch comments */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentController_createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Episode ID to comment on */
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Comment content (supports @mentions)
                     * @example Great episode! @john you should watch this
                     */
                    content: string;
                    /**
                     * @description Parent comment ID (if this is a reply)
                     * @example 673b2c3d4e5f6g7h8i9j0k1l
                     */
                    parentCommentId?: string;
                    /**
                     * @description User being replied to (for @mention display)
                     * @example 672fb3a25f348a0e8e9012d7
                     */
                    replyToUserId?: string;
                };
            };
        };
        responses: {
            /** @description Comment created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Parent comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Could not create comment */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentController_getCommentReplies: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: unknown;
                /** @description Replies per page */
                limit?: unknown;
            };
            header?: never;
            path: {
                /** @description Parent comment ID */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replies fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal server error - Could not fetch replies */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentController_deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID to delete */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Forbidden - You can only delete your own comments */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Could not delete comment */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentController_updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comment ID to update */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Updated comment content
                     * @example Updated: Great episode!
                     */
                    content: string;
                };
            };
        };
        responses: {
            /** @description Comment updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Forbidden - You can only edit your own comments */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error - Could not update comment */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
